//ACORDES MAIORES
var ACORDE_MAIOR = TONICA, TERCA_MAIOR, QUINTA_JUSTA;
var ACORDE_MAIOR_COM_SETIMA = TONICA, TERCA_MAIOR, QUINTA_JUSTA, SETIMA_MENOR;
var ACORDE_MAIOR_COM_SETIMA_MAIOR = TONICA, TERCA_MAIOR, QUINTA_JUSTA, SETIMA_MAIOR;

//ACORDES MENORES
var ACORDE_MENOR = TONICA, TERCA_MENOR, QUINTA_JUSTA;
var ACORDE_MENOR_COM_SETIMA = TONICA, TERCA_MENOR, QUINTA_JUSTA, SETIMA_MENOR;